import os
import psycopg

from psycopg.rows import dict_row
from fastapi import FastAPI
from pydantic import BaseModel
from datetime import datetime

DATABASE_URL = os.environ["DATABASE_URL"]

app = FastAPI()

class Item(BaseModel):
    name: str
    price: float
    is_offer: bool | None = None

class EventIn(BaseModel):
    name: str
    timestamp: datetime

class EventOut(EventIn):
    id: int

def init_db():
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur: # a handle to run SQL and fetch results
            cur.execute(""" 
                CREATE TABLE IF NOT EXISTS events (
                    id BIGSERIAL PRIMARY KEY,
                    name TEXT NOT NULL,
                    ts TIMESTAMPTZ NOT NULL
                );
            """)
        conn.commit()

def insert_event(event: EventIn):
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO events (name, ts) VALUES (%s, %s) RETURNING id;",
                (event.name, event.timestamp),
            )
            new_id = cur.fetchone()[0]
        conn.commit()
    return {"message": "Event received"}

def fetch_timeline():
    with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
        with conn.cursor() as cur:
            cur.execute(""" 
                SELECT id, name, ts AS timestamp
                FROM events
                ORDER BY ts ASC
                LIMIT 5000;
            """)
            # gets all rows generated by most recent SELECT
            rows = cur.fetchall(); 
    return {"events": rows}
@app.on_event("startup")
def on_startup():
    init_db()
@app.get("/")
def read_root():
    return {"Hello": "World"}
@app.get("/health")
def health():
    return {"ok": True}



#stores events into the events table
@app.post("/events")
async def create_event(event: EventIn):
    return insert_event(event)

#gets the timestamp and info of events
@app.get("/timeline")
async def timeline():
    return fetch_timeline()

@app.post("/reset")
def reset():
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE events RESTART IDENTITY;")
        conn.commit()
    return {"ok": True}

