import os
import psycopg

from psycopg.rows import dict_row
from fastapi import FastAPI
from pydantic import BaseModel
from datetime import datetime

DATABASE_URL = os.environ["DATABASE_URL"]

app = FastAPI()

class Item(BaseModel):
    name: str
    price: float
    is_offer: bool | None = None

class StartSessionIn(BaseModel):
    build_version: str

class EventIn(BaseModel):
    name: str
    timestamp: datetime

class EventOut(EventIn):
    id: int


def init_db():
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur: # a handle to run SQL and fetch results
            cur.execute(""" 
                CREATE EXTENSION IF NOT EXISTS pgcrypto;
                        
                CREATE TABLE IF NOT EXISTS sessions (
                    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                    created_at timestamptz NOT NULL DEFAULT now(),
                    build_version text NOT NULL,
                    client_id text NULL
                );
                        
                CREATE TABLE IF NOT EXISTS events (
                    id BIGSERIAL PRIMARY KEY,
                    session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
                    name TEXT NOT NULL,
                    ts TIMESTAMPTZ NOT NULL
                );
                
                CREATE INDEX IF NOT EXISTS idx_events_sessions_ts ON events(session_id, ts);
            """)
        conn.commit()

def insert_event(event: EventIn):
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO events (session_id, name, ts) VALUES (%s, %s, %s) RETURNING id;",
                (event.name, event.timestamp),
            )
            new_id = cur.fetchone()[0]
        conn.commit()
    return {"message": "Event received"}

def fetch_timeline():
    with psycopg.connect(DATABASE_URL, row_factory=dict_row) as conn:
        with conn.cursor() as cur:
            cur.execute(""" 
                SELECT id, name, ts AS timestamp
                FROM events
                WHERE session_id = %s
                ORDER BY ts ASC
                LIMIT 5000;
            """)
            # gets all rows generated by most recent SELECT
            rows = cur.fetchall(); 
    return {"events": rows}

def execute_sql(sql: str) -> None:
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute(sql)
        conn.commit()

@app.lifespan("startup")
def on_startup():
    init_db()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/items/{item_id}")
def read_item(item_id: int, q : str | None = None):
    return {"item_id": item_id, "q" :q}

@app.put("/items/{item_id}")
def update_item(item_id: int, item: Item):
    return {"item_name": item.name, "item_id": item_id}

@app.get("/health")
def health():
    return {"ok": True}

#gets the timestamp and info of events
@app.get("sessions/{sessions_id}/timeline")
def timeline():
    return fetch_timeline()

#stores events into the events table
@app.post("/events")
def create_event(event: EventIn):
    return insert_event(event)

@app.post("/sessions/start")
def start_session():
    return execute_sql("""
            INSERT INTO sessions (build_version, client_id)
            VALUES (%s, %s)
            RETURNING id;
        """)

@app.post("/sessions/end")
def end_session():
    return execute_sql("UPDATE sessions SET ended_at = now() WHERE id = %s;")

@app.post("/reset")
def reset():
    with psycopg.connect(DATABASE_URL) as conn:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE events, sessions RESTART IDENTITY CASCADE;")
        conn.commit()
    return {"ok": True}

